# Generated by Django 4.1.6 on 2023-02-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_on',
        ),
    ]
